language: node_js
node_js:
  - "10.15.3"
addons: 
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - npm install
  - npm install mocha -g
  - npm install -g karma-cli